spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PGURL}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database: postgresql

